name: e_commerce_app
description: "A new Flutter project."

publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

# --------------------------------- PACKAGES -------------------------------- #

dependencies:
  flutter:
    sdk: flutter

  # State Manager
  get: ^4.6.6

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

# ------------------------------- PACKAGES END ------------------------------ #

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

# ------------------------------- LOCAL ASSETS ------------------------------ #

assets:
  - assets/icons/brands/
  - assets/images/
  - assets/logos/

# ------------------------------- LOCAL FONTS ------------------------------- #

fonts:
  - family: coolvetica
    fonts:
      - asset: assets/fonts/coolvetica_regular.otf
        weight: 400
      - asset: assets/fonts/coolvetica_regular_italic.otf
        weight: 400
        style: italic
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-BoldItalic.ttf
        weight: 800
        style: italic
        